# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ['https://localhost:3000']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/': # Vous pouvez spécifier les chemins spécifiques comme '^/login'
            allow_origin: ['https://localhost:3000']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: []
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
