nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['https://localhost:3000', 'https://localhost:3001' ]
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'OPTIONS', 'DELETE', 'PUT']
        expose_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['https://localhost:3000', 'https://localhost:3001']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: []
            allow_methods: ['GET', 'POST', 'OPTIONS', 'DELETE', 'PUT']
            max_age: 3600
        '^/public/':
            allow_origin: ['https://localhost:3000', 'https://localhost:3001']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: []
            allow_methods: ['GET']
            max_age: 3600
