controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    trailing_slash_on_root: false
    options:
        recursive: true



api_login_check:
    path: /api/login_check

api_refresh_token:
    path: /api/token/refresh
    methods : ['POST']

api_token_invalidate:
    path: /api/token/invalidate

app_homepage:
    path: /
    controller: App\Controller\HomePageController::index


# config/routes.yaml


# ----------- API ACTIVITY ----------- #

api_activity_new_activity:
    path: /api/activity
    controller: App\Controller\API\ActiviteAPIController::addActivity
    methods: ['POST']

api_activity_update_activity:
    path: /api/activity/{id}
    controller: App\Controller\API\ActiviteAPIController::updateActivity
    methods: ['PUT']

api_activity_delete_activity:
    path: /api/activity/{id}
    controller: App\Controller\API\ActiviteAPIController::deleteActivity
    methods: ['DELETE']

api_activity_get_activity:
    path: /public/api/activity/{id}
    controller: App\Controller\API\ActiviteAPIController::getActivity
    methods: ['GET']

api_activity_get_activities:
    path: /public/api/activity
    controller: App\Controller\API\ActiviteAPIController::getActivities
    methods: ['GET']


# ------------- #

api_programmation_addnew:
    path: /api/programmation
    controller: App\Controller\API\ProgrammationAPIController::addProgrammation
    methods: ['POST']
    
api_programmation_delete:
    path: /api/programmation/{id}
    controller: App\Controller\API\ProgrammationAPIController::deleteProgrammation
    methods: ['DELETE']

api_programmation_get:
    path: /public/api/programmation/{id}
    controller: App\Controller\API\ProgrammationAPIController::getProgrammation
    methods: ['GET']

api_programmation_get_liste:
    path: /public/api/programmation
    controller: App\Controller\API\ProgrammationAPIController::getAllProgrammations
    methods: ['GET']

api_programmation_update:
    path: /api/programmation/{id}
    controller: App\Controller\API\ProgrammationAPIController::updateProgrammation
    methods: ['PUT']


# ----------- USER ------------- #

app_registration:
    path: /account
    controller: App\Controller\AccountController::registerAction


api_user_new_user:
    path: /api/user
    controller: App\Controller\API\UserAPIController::addUser
    methods: ['POST']


api_user_delete_user:
    path: /api/user/{id}
    controller: App\Controller\API\UserAPIController::deleteUser
    methods: ['DELETE']

api_user_update_user:
    path: /api/user/{id}
    controller: App\Controller\API\UserAPIController::updateUser
    methods: ['PUT']

api_user_get_users:
    path: /api/user
    controller: App\Controller\API\UserAPIController::getUsers
    methods: ['GET', 'OPTIONS']



api_commerce_addCommerce:
    path: /api/commerce
    controller: App\Controller\API\CommerceAPIController::addCommerce
    methods: ['POST']

