controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check


app_homepage:
    path: /
    controller: App\Controller\HomePageController::index


# config/routes.yaml

app_registration:
    path: /account
    controller: App\Controller\AccountController::registerAction


api_user_new_user:
    path: /api/user/addnew
    controller: App\Controller\UserController::addUser
    methods: ['POST']


api_user_remove_user:
    path: /api/user/remove
    controller: App\Controller\UserController::removeUser
    methods: ['DELETE']
