# config/services.yaml

parameters:
    # Définir les paramètres ici, si nécessaire
    mongodb_url: '%env(resolve:MONGODB_URL)%'
    mongodb_db: '%env(resolve:MONGODB_DB)%'

services:
    # Configuration par défaut pour les services
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Enregistrement automatique des services

    # Création automatique des services pour les classes dans le répertoire src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Définition explicite des services
    App\EventListener\AuthenticationSuccessListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }

    Doctrine\Persistence\ManagerRegistry: '@doctrine_mongodb'

    App\Controller\CustomerLoginController:
        public: true
        autowire: true
        autoconfigure: true

    App\Repository\ActiviteRepository:
        arguments:
            $dm: '@doctrine_mongodb.odm.document_manager'
        calls:
            - setLogger: ['@logger']

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Repository\ArtisteRepository:
        arguments:
            $dm: '@doctrine_mongodb.odm.document_manager'
        calls:
            - setLogger: ['@logger']

    App\Repository\CommerceRepository:
        arguments:
            $dm: '@doctrine_mongodb.odm.document_manager'
        calls:
            - setLogger: ['@logger']

    App\EventSubscriber\MarkerSubscriber:
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber }

    App\EventSubscriber\ArtisteSubscriber:
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber }

    App\EventSubscriber\ActiviteSubscriber:
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber }

    App\EventListener\CorsListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    Symfony\Component\Dotenv\Command\DotenvDumpCommand: ~
